'''
Step 1: Load the CSV
Step 2: Look at the first few rows
Step 3: Check how many rows and columns there are
Step 4: Separate the 63 landmark values from the label
Step 5: Split into training and testing data
Step 6: Train a simple classifier
Step 7: Test the classifier
Step 8: Check accuracy
'''


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import joblib

df = pd.read_csv('dataset.csv',header= None)
X = df.iloc[:, :-1] # all rows, all columns except the last column
y = df.iloc[:, -1] #the last row

X_train, X_test, y_train, y_test = train_test_split(
  X,y , random_state=104,test_size=0.25, shuffle=True)

KNNClassifier = KNeighborsClassifier(n_neighbors=5)
KNNClassifier.fit(X_train, y_train) #Learn the pattern between the landmark numbers and the labels A, B, C.
y_pred= KNNClassifier.predict(X_test) #Use the trained model to guess the labels for the test examples and store the predictions in y_pred
joblib.dump(KNNClassifier, "asl_knn_model.joblib")  #save it to a file


print(y_test.head()) #show first 5 rows
print(y_pred[:5]) #start from the beginning and stop at position 5

accuracy = accuracy_score(y_test, y_pred) # compares real answers vs model guesses
print(accuracy)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

31     A
18     A
10     A
64     B
134    C
Name: 63, dtype: object
['A' 'A' 'A' 'B' 'C']
1.0
[[17  0  0]
 [ 0 13  0]
 [ 0  0  8]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00        17
           B       1.00      1.00      1.00        13
           C       1.00      1.00      1.00         8

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [ ]:
loaded_model = joblib.load("asl_knn_model.joblib") #bring it back later
loaded_predictions = loaded_model.predict(X_test)
accuracy_score(y_test, loaded_predictions)

1.0